# Use the official OpenJDK base image
FROM openjdk:11

# Set the working directory inside the container
WORKDIR /app

# Copy the Java project into the container
COPY . /app

# Run the Java application
CMD ["java", "-cp", ".", "Controller"]